### ISSUE TITLE
Bug in migration create table mail_users

### ISSUE THREAD

**Issue by tlappe** [jeboehm/mailserver-admin#1]
https://github.com/jeboehm/mailserver-admin/blob/255f8e12861cc0dd6d2e20024775d4f003753509/src/Migrations/Version20180320164351.php#L44

The unique index UNIQ_1483A5E95E237E06(name) prevents my system to upgrade to the new database schema. Dropping this index in the next migration is too late because the postUp() method throws an SQL exception at inserting the users into mail_users. There are many different email addresses with, e.g. info@... So the migration process is stopped at this point, the unique index won't be dropped and the web container stops working.

**Comment by jeboehm** [comment]
Hi @tlappe 
you are right! I hope you have managed to migrate your users.
The wrong unique index is removed in a [later migration](https://github.com/jeboehm/mailserver-admin/blob/5429ef2c891080f2f5af6c826f00b02cb825f831/src/Migrations/Version20180320171339.php#L26).  

I'll close this bug because newer images are relying on an updated database dump.
